version: '3'

services:
  iris:
    build:
      dockerfile: Dockerfile-iris
      context: '.'
    container_name: iris
    restart: always
    tty: true
    ports:
      - "52773:52773"
      - "1972:1972"
    volumes:
      - .:/app
      - /var/data/iris:/irisapp:rw

  questy:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile-questy
      context: '.'
    image: questy
    restart: always
    tty: true
    ports:
      - "8080:80"
    links:
      - iris
